export interface CharacterInfo {
  name: string;
  quote: string;
  description: string;
}

export const QUIZ_QUESTIONS = [
  {
    question: "What's your preferred approach to challenges during a crisis?",
    options: ["Head-on confrontation, I don't back down.", "Strategic planning, I analyze first.", "Adapt and improvise, whatever works.", "Avoid if possible, it's too much effort."],
    weights: { "Head-on confrontation": "Goku", "Strategic planning": "L Lawliet", "Adapt and improvise": "Joseph Joestar", "Avoid if possible": "Saitama" },
    traits: { "Head-on confrontation": "Valiant Hero", "Strategic planning": "Analytical Mastermind", "Adapt and improvise": "Witty Trickster", "Avoid if possible": "Restful Soul" }
  },
  {
    question: "How do you treat your allies?",
    options: ["Protect them at all costs, they are my motivation.", "They are useful tools for my success.", "Partners in crime, let's have fun.", "Keep them at a distance, it's safer for everyone."],
    weights: { "Protect them at all costs": "Tanjiro", "They are useful tools": "Aizen", "Partners in crime": "Luffy", "Keep them at a distance": "Kiyotaka Ayanokoji" },
    traits: { "Protect them at all costs": "Devoted Protector", "They are useful tools": "Calculated Manipulator", "Partners in crime": "Free-spirited Companion", "Keep them at a distance": "Aloof Intellectual" }
  },
  {
    question: "What's your ultimate goal in life?",
    options: ["Become the absolute strongest.", "Find the hidden truth.", "Protect my peaceful, simple life.", "Change the corrupt world."],
    weights: { "Become the strongest": "Ichigo Kurosaki", "Find the truth": "L Lawliet", "Protect my peaceful life": "Yoshikage Kira", "Change the world": "Eren Yeager" },
    traits: { "Become the strongest": "Ambitions Conqueror", "Find the truth": "Curious Seeker", "Protect my peaceful life": "Tranquil Observer", "Change the world": "Revolutionary Leader" }
  },
  {
    question: "How do you handle failures?",
    options: ["I learn from them and get stronger.", "I get angry and try harder to crush it.", "I laugh it off and move to the next thing.", "I beat myself up and hide away."],
    weights: { "I learn from them and get stronger.": "Gon Freecss", "I get angry and try harder to crush it.": "Bakugo", "I laugh it off and move to the next thing.": "Dazai Osamu", "I beat myself up and hide away.": "Airi Sakura" },
    traits: { "I learn from them and get stronger.": "Resilient Learner", "I get angry and try harder to crush it.": "Intense Competitor", "I laugh it off and move to the next thing.": "Carefree Soul", "I beat myself up and hide away.": "Sensitive Soul" }
  },
  {
    question: "What environment do you thrive in?",
    options: ["Chaotic and action-packed.", "Quiet and organized library/office.", "Somewhere I can roam freely.", "A familiar place with people I know."],
    weights: { "Chaotic and action-packed.": "Guts", "Quiet and organized library/office.": "Hiyori Shiina", "Somewhere I can roam freely.": "Luffy", "A familiar place with people I know.": "Kei Karuizawa" },
    traits: { "Chaotic and action-packed.": "Adrenaline Junkie", "Quiet and organized library/office.": "Intellectual Introvert", "Somewhere I can roam freely.": "Adventurous Wanderer", "A familiar place with people I know.": "Secure Socialite" }
  },
  {
    question: "How do you spend your free time?",
    options: ["Training until I drop.", "Reading and planning.", "Partying with friends.", "Hiding and playing games."],
    weights: { "Training until I drop.": "Goku", "Reading and planning.": "L Lawliet", "Partying with friends.": "Luffy", "Hiding and playing games.": "King" },
    traits: { "Training until I drop.": "Dedicated Athlete", "Reading and planning.": "Intellectual Stratagy", "Partying with friends.": "Social Butterfly", "Hiding and playing games.": "Reluctant Hero" }
  },
  {
    question: "What is your greatest strength?",
    options: ["My fighting spirit.", "My intellect.", "My adaptability.", "My ability to influence others."],
    weights: { "My fighting spirit.": "Naruto Uzumaki", "My intellect.": "Light Yagami", "My adaptability.": "Killua", "My ability to influence others.": "Aizen" },
    traits: { "My fighting spirit.": "Unstoppable Force", "My intellect.": "Master Strategist", "My adaptability.": "Shifting Shadow", "My ability to influence others.": "Charismatic Leader" }
  }
];

export const CHARACTER_DATA: Record<string, CharacterInfo> = {
  "Sukuna": { name: "Sukuna", quote: "You are my special.", description: "The King of Curses, known for his immense power and ruthless nature." },
  "Gun Park": { name: "Gun Park", quote: "Life is a game.", description: "The legendary fighter from Lookism." },
  "Yuji": { name: "Yuji", quote: "I just want people to have a proper death.", description: "The vessel of Sukuna, determined to save people." },
  "Rin Itoshi": { name: "Rin Itoshi", quote: "I'll destroy everything.", description: "A top-tier striker from Blue Lock." },
  "Gojo": { name: "Gojo", quote: "Throughout heaven and earth, I alone am the honored one.", description: "The strongest jujutsu sorcerer." },
  "Eren Yeager": { name: "Eren Yeager", quote: "I will keep moving forward.", description: "Determined to break the cycle of hatred." },
  "Luffy": { name: "Luffy", quote: "I'm going to be the Pirate King!", description: "Captain of the Straw Hat Pirates." },
  "Zoro": { name: "Zoro", quote: "I'll never lose again!", description: "The swordsman of the Straw Hat Pirates." },
  "Naruto Uzumaki": { name: "Naruto Uzumaki", quote: "Believe it!", description: "The Seventh Hokage of Konoha." },
  "Sasuke Uchiha": { name: "Sasuke Uchiha", quote: "My goal is in the darkness.", description: "The last survivor of the Uchiha clan." },
  "Kakashi": { name: "Kakashi", quote: "Those who break the rules are scum, but those who abandon their friends are worse than scum.", description: "The Copy Ninja of the Hidden Leaf." },
  "Killua": { name: "Killua", quote: "Baka.", description: "An elite assassin prodigy." },
  "Gon Freecss": { name: "Gon Freecss", quote: "I'll find you, Dad!", description: "A young boy searching for his father." },
  "Levi Ackerman": { name: "Levi Ackerman", quote: "Dedicate your heart.", description: "Humanity's strongest soldier." },
  "Light Yagami": { name: "Light Yagami", quote: "I'll become the God of this new world.", description: "A genius student who found the Death Note." },
  "L Lawliet": { name: "L Lawliet", quote: "I am Justice.", description: "The world's greatest detective." },
  "Goku": { name: "Goku", quote: "I am the hope of the universe.", description: "A powerful Saiyan warrior." },
  "Vegeta": { name: "Vegeta", quote: "I am the Prince of all Saiyans!", description: "The proud Saiyan Prince." },
  "Ichigo Kurosaki": { name: "Ichigo Kurosaki", quote: "I protect what's mine.", description: "A substitute Shinigami." },
  "Aizen": { name: "Aizen", quote: "Since when were you under the impression that I wasn't using Kyoka Suigetsu?", description: "A mastermind with complex plans." },
  "Saitama": { name: "Saitama", quote: "I'm just a guy who's a hero for fun.", description: "The strongest hero who wins with one punch." },
  "Garou": { name: "Garou", quote: "I will be the ultimate monster.", description: "A martial arts prodigy who hunts heroes." },
  "Tanjiro": { name: "Tanjiro", quote: "Don't give up!", description: "A kind-hearted demon slayer." },
  "Nezuko": { name: "Nezuko", quote: "Mmph mmmph!", description: "A protective demon sister who travels with her brother." },
  "Inosuke": { name: "Inosuke", quote: "PIG ASSAULT!", description: "A wild demon slayer with a boar mask." },
  "Zenitsu": { name: "Zenitsu", quote: "Nezuko-chan!", description: "A demon slayer who is brave when asleep." },
  "Rengoku": { name: "Rengoku", quote: "Set your heart ablaze!", description: "The Flame Hashira." },
  "Toji Fushiguro": { name: "Toji Fushiguro", quote: "I don't need cursed energy.", description: "The Sorcerer Killer." },
  "Megumi Fushiguro": { name: "Megumi Fushiguro", quote: "With this treasure, I summon...", description: "A calm, talented sorcerer who uses the Ten Shadows technique." },
  "Choso": { name: "Choso", quote: "I am a brother.", description: "A special grade cursed womb." },
  "Thorfinn": { name: "Thorfinn", quote: "I have no enemies.", description: "A warrior seeking redemption." },
  "Askeladd": { name: "Askeladd", quote: "A warrior's death is not for me.", description: "A charismatic and cunning leader." },
  "Ken Kaneki": { name: "Ken Kaneki", quote: "I am a ghoul.", description: "A college student turned half-ghoul." },
  "Mob (Shigeo)": { name: "Mob (Shigeo)", quote: "I'm just a normal middle schooler.", description: "A powerful psychic." },
  "Reigen Arataka": { name: "Reigen Arataka", quote: "Don't sweat the small stuff.", description: "A charismatic con artist and psychic." },
  "Rimuru Tempest": { name: "Rimuru Tempest", quote: "I'm not a bad slime!", description: "A slime with immense power." },
  "Sung Jin-Woo": { name: "Sung Jin-Woo", quote: "Arise.", description: "The Shadow Monarch." },
  "Guts": { name: "Guts", quote: "I am the struggler.", description: "A legendary mercenary warrior." },
  "Griffith": { name: "Griffith", quote: "I will have my own kingdom.", description: "A charismatic and ambitious leader." },
  "Edward Elric": { name: "Edward Elric", quote: "Equivalent Exchange!", description: "The Fullmetal Alchemist." },
  "Roy Mustang": { name: "Roy Mustang", quote: "I'll burn it all.", description: "The Flame Alchemist." },
  "Dazai Osamu": { name: "Dazai Osamu", quote: "It's a wonderful day for suicide.", description: "A mysterious detective." },
  "Chuuya Nakahara": { name: "Chuuya Nakahara", quote: "I'll crush you.", description: "A powerful ability user." },
  "Baki Hanma": { name: "Baki Hanma", quote: "I want to be stronger.", description: "A legendary martial artist." },
  "Isagi Yoichi": { name: "Isagi Yoichi", quote: "I'll become the best in the world.", description: "A rising soccer star." },
  "Mikasa Ackerman": { name: "Mikasa Ackerman", quote: "The world is cruel, but also very beautiful.", description: "Eren's childhood friend and a skilled soldier." },
  "Armin Arlert": { name: "Armin Arlert", quote: "A person who cannot sacrifice anything, can change nothing.", description: "A brilliant strategist." },
  "Erwin Smith": { name: "Erwin Smith", quote: "They want to know what the result of their hearts is! Because the fighting we do doesn't end here!", description: "The 13th Commander of the Survey Corps." },
  "Hange Zoë": { name: "Hange Zoë", quote: "There's nothing more exciting than learning about the unknown!", description: "A passionate researcher of Titans." },
  "Reiner Braun": { name: "Reiner Braun", quote: "I'll do it. I'll rid the world of the Titans.", description: "The Armored Titan." },
  "Bertholdt Hoover": { name: "Bertholdt Hoover", quote: "Who would want to be a murderer if they could avoid it?", description: "The Colossal Titan." },
  "Annie Leonhart": { name: "Annie Leonhart", quote: "...", description: "The Female Titan." },
  "Zeke Yeager": { name: "Zeke Yeager", quote: "Let's put an end to this cycle in our generation.", description: "The Beast Titan." },
  "Sasha Braus": { name: "Sasha Braus", quote: "Meat!", description: "A talented scout with a love for food." },
  "Jean Kirstein": { name: "Jean Kirstein", quote: "I want to live a life I can be proud of.", description: "A pragmatic member of the Survey Corps." },
  "Shoyo Hinata": { name: "Shoyo Hinata", quote: "I might be small, but I can fly!", description: "A determined volleyball player." },
  "Tobio Kageyama": { name: "Tobio Kageyama", quote: "I'll be the one to toss to you.", description: "A genius setter." },
  "Toru Oikawa": { name: "Toru Oikawa", quote: "If you're going to hit it, hit it until it breaks.", description: "The ace setter of Aoba Johsai." },
  "Kenma Kozume": { name: "Kenma Kozume", quote: "I'm not good with people.", description: "A calm and strategic setter." },
  "Tetsuro Kuroo": { name: "Tetsuro Kuroo", quote: "We're like the blood in our veins. We must flow without stopping.", description: "Captain of Nekoma High." },
  "Kotaro Bokuto": { name: "Kotaro Bokuto", quote: "HEY HEY HEY!", description: "The energetic ace of Fukurodani." },
  "Keiji Akaashi": { name: "Keiji Akaashi", quote: "I'm always here to cover for you.", description: "A calm setter." },
  "Wakatoshi Ushijima": { name: "Wakatoshi Ushijima", quote: "I will be the one to defeat you.", description: "The powerhouse ace of Shiratorizawa." },
  "Atsumu Miya": { name: "Atsumu Miya", quote: "I'm the best setter in the country.", description: "A talented and arrogant setter." },
  "Kei Tsukishima": { name: "Kei Tsukishima", quote: "It's just a club.", description: "A tactical middle blocker." },
  "Yu Nishinoya": { name: "Yu Nishinoya", quote: "I've got your back!", description: "An energetic libero." },
  "Daichi Sawamura": { name: "Daichi Sawamura", quote: "We're Karasuno!", description: "The reliable captain of Karasuno." },
  "Jonathan Joestar": { name: "Jonathan Joestar", quote: "I will not let you kill anyone else!", description: "A gentlemanly hero." },
  "Joseph Joestar": { name: "Joseph Joestar", quote: "Your next line is...", description: "A cunning and humorous hero." },
  "Jotaro Kujo": { name: "Jotaro Kujo", quote: "Yare yare daze.", description: "A stoic and powerful Stand user." },
  "Josuke Higashikata": { name: "Josuke Higashikata", quote: "Great!", description: "A kind-hearted Stand user with a pompadour." },
  "Giorno Giovanna": { name: "Giorno Giovanna", quote: "I have a dream.", description: "A determined Stand user." },
  "Jolyne Cujoh": { name: "Jolyne Cujoh", quote: "I'll break out of this prison!", description: "A resilient Stand user." },
  "Dio Brando": { name: "Dio Brando", quote: "Kono Dio da!", description: "The ultimate villain." },
  "Yoshikage Kira": { name: "Yoshikage Kira", quote: "I just want a quiet life.", description: "A serial killer who wants peace." },
  "Diavolo": { name: "Diavolo", quote: "I am the emperor!", description: "A powerful and mysterious villain." },
  "Enrico Pucci": { name: "Enrico Pucci", quote: "Do you believe in gravity?", description: "A devoted follower of Dio." },
  "Bruno Bucciarati": { name: "Bruno Bucciarati", quote: "The way of the gangster...", description: "A leader with a strong sense of justice." },
  "Jean Pierre Polnareff": { name: "Jean Pierre Polnareff", quote: "Silver Chariot!", description: "A French swordsman." },
  "Misa Amane": { name: "Misa Amane", quote: "Light!", description: "Light's devoted follower." },
  "Ryuk": { name: "Ryuk", quote: "Humans are so interesting.", description: "A Shinigami." },
  "Near (Nate River)": { name: "Near (Nate River)", quote: "I'll solve this puzzle.", description: "A genius rival to L." },
  "Mello (Mihael Keehl)": { name: "Mello (Mihael Keehl)", quote: "I'll be the one to win.", description: "A determined and impulsive rival to Near." },
  "Alphonse Elric": { name: "Alphonse Elric", quote: "Brother!", description: "Edward's kind younger brother." },
  "Riza Hawkeye": { name: "Riza Hawkeye", quote: "I'll protect you, Colonel.", description: "Mustang's loyal subordinate." },
  "Winry Rockbell": { name: "Winry Rockbell", quote: "I'll fix your automail!", description: "A talented automail mechanic." },
  "Scar": { name: "Scar", quote: "I will destroy the alchemists.", description: "A vengeful Ishvalan survivor." },
  "King Bradley": { name: "King Bradley", quote: "I am the leader of this nation.", description: "A powerful and cold-hearted leader." },
  "Envy": { name: "Envy", quote: "Pitiful humans.", description: "A shape-shifting Homunculus." },
  "Greed": { name: "Greed", quote: "I want everything.", description: "A Homunculus with a thirst for power." },
  "Genos": { name: "Genos", quote: "I need more power.", description: "Saitama's cyborg disciple." },
  "Tatsumaki (Tornado of Terror)": { name: "Tatsumaki (Tornado of Terror)", quote: "Move it, you pest!", description: "A powerful psychic hero." },
  "Fubuki (Blizzard of Hell)": { name: "Fubuki (Blizzard of Hell)", quote: "I'll show you my strength.", description: "The leader of the Blizzard Group." },
  "Bang (Silver Fang)": { name: "Bang (Silver Fang)", quote: "Water Stream Rock Smashing Fist!", description: "A wise martial arts master." },
  "Speed-o'-Sound Sonic": { name: "Speed-o'-Sound Sonic", quote: "Saitama!", description: "A ninja who wants to defeat Saitama." },
  "King": { name: "King", quote: "I might look like the strongest man, but I'm actually just a gamer.", description: "Known as the strongest man on Earth, but essentially harmless." },

  "Kiyotaka Ayanokoji": { name: "Kiyotaka Ayanokoji", quote: "I have never thought of others as allies or friends. I only care about winning.", description: "A mysterious, highly intelligent student who tries to live a low-profile life." },
  "Suzune Horikita": { name: "Suzune Horikita", quote: "I don't need friends. I only need results.", description: "A cold, pragmatic, and highly intelligent student striving to reach Class A." },
  "Kei Karuizawa": { name: "Kei Karuizawa", quote: "I'll do whatever it takes to survive.", description: "A popular student with a traumatic past who relies on alliances for protection." },
  "Kikyou Kushida": { name: "Kikyou Kushida", quote: "I want to be loved by everyone.", description: "A student who hides a sinister, manipulative personality behind a cheerful facade." },
  "Kakeru Ryuuen": { name: "Kakeru Ryuuen", quote: "I like to crush those who think they're superior.", description: "An aggressive and manipulative class leader who uses underhanded tactics." },
  "Honami Ichinose": { name: "Honami Ichinose", quote: "I will protect my class no matter what.", description: "A kind, popular, and self-sacrificing class leader." },
  "Arisu Sakayanagi": { name: "Arisu Sakayanagi", quote: "I am the only one who can truly challenge you.", description: "A strategic genius who leads Class A with confidence." },
  "Yousuke Hirata": { name: "Yousuke Hirata", quote: "I will do anything to keep the class united.", description: "A selfless and responsible student dedicated to class harmony." },
  "Ken Sudo": { name: "Ken Sudo", quote: "I'll show them my strength on the court.", description: "A hot-headed, athletic student who is impulsive but passionate." },
  "Airi Sakura": { name: "Airi Sakura", quote: "I... I'm not good at interacting with others.", description: "A shy, introverted student with hidden artistic talents." },
  "Manabu Horikita": { name: "Manabu Horikita", quote: "You lack the resolve to change things.", description: "The strict and formidable Student Council President." },
  "Sae Chabashira": { name: "Sae Chabashira", quote: "Don't think I'll help you for free.", description: "A cunning teacher who pushes her students to grow through challenges." },
  "Miyabi Nagumo": { name: "Miyabi Nagumo", quote: "I will reshape the school in my own image.", description: "An ambitious and dominant Student Council President." },
  "Maya Sato": { name: "Maya Sato", quote: "Isn't it obvious?", description: "A girl who is outgoing and easily influenced." },
  "Kohei Katsuragi": { name: "Kohei Katsuragi", quote: "Stability is the most important thing.", description: "A cautious and pragmatic leader focused on steady progress." },
  "Hiyori Shiina": { name: "Hiyori Shiina", quote: "The library is a peaceful place.", description: "A bookworm who values intellect and tranquility." },
  "Takuya Yagami": { name: "Takuya Yagami", quote: "I will prove my superiority.", description: "A highly capable student hiding his true prowess." },
  "Ichika Amasawa": { name: "Ichika Amasawa", quote: "I'm just a curious observer.", description: "A playful yet manipulative student from the White Room." },
};

export const COLOUR_CHARACTER_MAP: Record<string, string> = {
  "red": "Goku",
  "blue": "L Lawliet",
  "green": "Tanjiro",
  "yellow": "Luffy",
  "black": "Sukuna",
  "white": "Eren Yeager",
  "purple": "Aizen",
  "orange": "Naruto Uzumaki"
};

export const FOOD_CHARACTER_MAP: Record<string, string> = {
  "sushi": "Gojo",
  "ramen": "Naruto Uzumaki",
  "meat": "Sasha Braus",
  "pizza": "L Lawliet",
  "sweets": "Luffy",
  "burgers": "Saitama",
  "curry": "Tanjiro",
  "fish": "Killua"
};
