export interface CharacterInfo {
  name: string;
  quote: string;
  description: string;
}

export const CHARACTER_DATA: Record<string, CharacterInfo> = {
  "Sukuna": { name: "Sukuna", quote: "I do what I please. That is the essence of my existence.", description: "The King of Curses, known for his immense power and ruthless nature." },
  "Gun Park": { name: "Gun Park", quote: "Life is a game.", description: "The legendary fighter from Lookism." },
  "Yuji": { name: "Yuji", quote: "I just want people to have a proper death.", description: "The vessel of Sukuna, determined to save people." },
  "Rin Itoshi": { name: "Rin Itoshi", quote: "I'll destroy everything.", description: "A top-tier striker from Blue Lock." },
  "Gojo": { name: "Gojo", quote: "Throughout heaven and earth, I alone am the honored one.", description: "The strongest jujutsu sorcerer." },
  "Eren Yeager": { name: "Eren Yeager", quote: "I will keep moving forward.", description: "Determined to break the cycle of hatred." },
  "Luffy": { name: "Luffy", quote: "I'm going to be the Pirate King!", description: "Captain of the Straw Hat Pirates." },
  "Zoro": { name: "Zoro", quote: "I'll never lose again!", description: "The swordsman of the Straw Hat Pirates." },
  "Naruto Uzumaki": { name: "Naruto Uzumaki", quote: "I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way!", description: "The Seventh Hokage of Konoha." },
  "Sasuke Uchiha": { name: "Sasuke Uchiha", quote: "My goal is in the darkness.", description: "The last survivor of the Uchiha clan." },
  "Kakashi": { name: "Kakashi", quote: "Those who break the rules are scum, but those who abandon their friends are worse than scum.", description: "The Copy Ninja of the Hidden Leaf." },
  "Killua": { name: "Killua", quote: "I'm an assassin, after all.", description: "An elite assassin prodigy." },
  "Gon Freecss": { name: "Gon Freecss", quote: "I'll find you, Dad!", description: "A young boy searching for his father." },
  "Levi Ackerman": { name: "Levi Ackerman", quote: "Dedicate your heart.", description: "Humanity's strongest soldier." },
  "Light Yagami": { name: "Light Yagami", quote: "I'll become the God of this new world.", description: "A genius student who found the Death Note." },
  "L Lawliet": { name: "L Lawliet", quote: "If you use your head, you won't get fat even if you eat sweets.", description: "The world's greatest detective." },
  "Goku": { name: "Goku", quote: "I am the hope of the universe. I am the answer to all living things that cry out for peace.", description: "A powerful Saiyan warrior." },
  "Vegeta": { name: "Vegeta", quote: "I am the Prince of all Saiyans!", description: "The proud Saiyan Prince." },
  "Ichigo Kurosaki": { name: "Ichigo Kurosaki", quote: "I protect what's mine.", description: "A substitute Shinigami." },
  "Aizen": { name: "Aizen", quote: "Since when were you under the impression that I wasn't using Kyoka Suigetsu?", description: "A mastermind with complex plans." },
  "Saitama": { name: "Saitama", quote: "I'm just a guy who's a hero for fun.", description: "The strongest hero who wins with one punch." },
  "Garou": { name: "Garou", quote: "I will be the ultimate monster.", description: "A martial arts prodigy who hunts heroes." },
  "Tanjiro": { name: "Tanjiro", quote: "Don't give up!", description: "A kind-hearted demon slayer." },
  "Nezuko": { name: "Nezuko", quote: "Mmph mmmph!", description: "A protective demon sister who travels with her brother." },
  "Inosuke": { name: "Inosuke", quote: "PIG ASSAULT!", description: "A wild demon slayer with a boar mask." },
  "Zenitsu": { name: "Zenitsu", quote: "Nezuko-chan!", description: "A demon slayer who is brave when asleep." },
  "Rengoku": { name: "Rengoku", quote: "Set your heart ablaze!", description: "The Flame Hashira." },
  "Toji Fushiguro": { name: "Toji Fushiguro", quote: "I don't need cursed energy.", description: "The Sorcerer Killer." },
  "Megumi Fushiguro": { name: "Megumi Fushiguro", quote: "With this treasure, I summon...", description: "A calm, talented sorcerer who uses the Ten Shadows technique." },
  "Choso": { name: "Choso", quote: "I am a brother.", description: "A special grade cursed womb." },
  "Thorfinn": { name: "Thorfinn", quote: "I have no enemies.", description: "A warrior seeking redemption." },
  "Askeladd": { name: "Askeladd", quote: "A warrior's death is not for me.", description: "A charismatic and cunning leader." },
  "Ken Kaneki": { name: "Ken Kaneki", quote: "I am a ghoul.", description: "A college student turned half-ghoul." },
  "Mob (Shigeo)": { name: "Mob (Shigeo)", quote: "I'm just a normal middle schooler.", description: "A powerful psychic." },
  "Reigen Arataka": { name: "Reigen Arataka", quote: "Don't sweat the small stuff.", description: "A charismatic con artist and psychic." },
  "Rimuru Tempest": { name: "Rimuru Tempest", quote: "I'm not a bad slime!", description: "A slime with immense power." },
  "Sung Jin-Woo": { name: "Sung Jin-Woo", quote: "Arise.", description: "The Shadow Monarch." },
  "Guts": { name: "Guts", quote: "I am the struggler.", description: "A legendary mercenary warrior." },
  "Griffith": { name: "Griffith", quote: "I will have my own kingdom.", description: "A charismatic and ambitious leader." },
  "Edward Elric": { name: "Edward Elric", quote: "Equivalent Exchange!", description: "The Fullmetal Alchemist." },
  "Roy Mustang": { name: "Roy Mustang", quote: "I'll burn it all.", description: "The Flame Alchemist." },
  "Dazai Osamu": { name: "Dazai Osamu", quote: "It's a wonderful day for suicide.", description: "A mysterious detective." },
  "Chuuya Nakahara": { name: "Chuuya Nakahara", quote: "I'll crush you.", description: "A powerful ability user." },
  "Baki Hanma": { name: "Baki Hanma", quote: "I want to be stronger.", description: "A legendary martial artist." },
  "Isagi Yoichi": { name: "Isagi Yoichi", quote: "I'll become the best in the world.", description: "A rising soccer star." },
  "Mikasa Ackerman": { name: "Mikasa Ackerman", quote: "The world is cruel, but also very beautiful.", description: "Eren's childhood friend and a skilled soldier." },
  "Armin Arlert": { name: "Armin Arlert", quote: "A person who cannot sacrifice anything, can change nothing.", description: "A brilliant strategist." },
  "Erwin Smith": { name: "Erwin Smith", quote: "They want to know what the result of their hearts is! Because the fighting we do doesn't end here!", description: "The 13th Commander of the Survey Corps." },
  "Hange Zoë": { name: "Hange Zoë", quote: "There's nothing more exciting than learning about the unknown!", description: "A passionate researcher of Titans." },
  "Reiner Braun": { name: "Reiner Braun", quote: "I'll do it. I'll rid the world of the Titans.", description: "The Armored Titan." },
  "Bertholdt Hoover": { name: "Bertholdt Hoover", quote: "Who would want to be a murderer if they could avoid it?", description: "The Colossal Titan." },
  "Annie Leonhart": { name: "Annie Leonhart", quote: "...", description: "The Female Titan." },
  "Zeke Yeager": { name: "Zeke Yeager", quote: "Let's put an end to this cycle in our generation.", description: "The Beast Titan." },
  "Sasha Braus": { name: "Sasha Braus", quote: "Meat!", description: "A talented scout with a love for food." },
  "Jean Kirstein": { name: "Jean Kirstein", quote: "I want to live a life I can be proud of.", description: "A pragmatic member of the Survey Corps." },
  "Shoyo Hinata": { name: "Shoyo Hinata", quote: "I might be small, but I can fly!", description: "A determined volleyball player." },
  "Tobio Kageyama": { name: "Tobio Kageyama", quote: "I'll be the one to toss to you.", description: "A genius setter." },
  "Toru Oikawa": { name: "Toru Oikawa", quote: "If you're going to hit it, hit it until it breaks.", description: "The ace setter of Aoba Johsai." },
  "Kenma Kozume": { name: "Kenma Kozume", quote: "I'm not good with people.", description: "A calm and strategic setter." },
  "Tetsuro Kuroo": { name: "Tetsuro Kuroo", quote: "We're like the blood in our veins. We must flow without stopping.", description: "Captain of Nekoma High." },
  "Kotaro Bokuto": { name: "Kotaro Bokuto", quote: "HEY HEY HEY!", description: "The energetic ace of Fukurodani." },
  "Keiji Akaashi": { name: "Keiji Akaashi", quote: "I'm always here to cover for you.", description: "A calm setter." },
  "Wakatoshi Ushijima": { name: "Wakatoshi Ushijima", quote: "I will be the one to defeat you.", description: "The powerhouse ace of Shiratorizawa." },
  "Atsumu Miya": { name: "Atsumu Miya", quote: "I'm the best setter in the country.", description: "A talented and arrogant setter." },
  "Kei Tsukishima": { name: "Kei Tsukishima", quote: "It's just a club.", description: "A tactical middle blocker." },
  "Yu Nishinoya": { name: "Yu Nishinoya", quote: "I've got your back!", description: "An energetic libero." },
  "Daichi Sawamura": { name: "Daichi Sawamura", quote: "We're Karasuno!", description: "The reliable captain of Karasuno." },
  "Jonathan Joestar": { name: "Jonathan Joestar", quote: "I will not let you kill anyone else!", description: "A gentlemanly hero." },
  "Joseph Joestar": { name: "Joseph Joestar", quote: "Your next line is...", description: "A cunning and humorous hero." },
  "Jotaro Kujo": { name: "Jotaro Kujo", quote: "Yare yare daze.", description: "A stoic and powerful Stand user." },
  "Josuke Higashikata": { name: "Josuke Higashikata", quote: "Great!", description: "A kind-hearted Stand user with a pompadour." },
  "Giorno Giovanna": { name: "Giorno Giovanna", quote: "I have a dream.", description: "A determined Stand user." },
  "Jolyne Cujoh": { name: "Jolyne Cujoh", quote: "I'll break out of this prison!", description: "A resilient Stand user." },
  "Dio Brando": { name: "Dio Brando", quote: "Kono Dio da!", description: "The ultimate villain." },
  "Yoshikage Kira": { name: "Yoshikage Kira", quote: "I just want a quiet life.", description: "A serial killer who wants peace." },
  "Diavolo": { name: "Diavolo", quote: "I am the emperor!", description: "A powerful and mysterious villain." },
  "Enrico Pucci": { name: "Enrico Pucci", quote: "Do you believe in gravity?", description: "A devoted follower of Dio." },
  "Bruno Bucciarati": { name: "Bruno Bucciarati", quote: "The way of the gangster...", description: "A leader with a strong sense of justice." },
  "Jean Pierre Polnareff": { name: "Jean Pierre Polnareff", quote: "Silver Chariot!", description: "A French swordsman." },
  "Misa Amane": { name: "Misa Amane", quote: "Light!", description: "Light's devoted follower." },
  "Ryuk": { name: "Ryuk", quote: "Humans are so interesting.", description: "A Shinigami." },
  "Near (Nate River)": { name: "Near (Nate River)", quote: "I'll solve this puzzle.", description: "A genius rival to L." },
  "Mello (Mihael Keehl)": { name: "Mello (Mihael Keehl)", quote: "I'll be the one to win.", description: "A determined and impulsive rival to Near." },
  "Alphonse Elric": { name: "Alphonse Elric", quote: "Brother!", description: "Edward's kind younger brother." },
  "Riza Hawkeye": { name: "Riza Hawkeye", quote: "I'll protect you, Colonel.", description: "Mustang's loyal subordinate." },
  "Winry Rockbell": { name: "Winry Rockbell", quote: "I'll fix your automail!", description: "A talented automail mechanic." },
  "Scar": { name: "Scar", quote: "I will destroy the alchemists.", description: "A vengeful Ishvalan survivor." },
  "King Bradley": { name: "King Bradley", quote: "I am the leader of this nation.", description: "A powerful and cold-hearted leader." },
  "Envy": { name: "Envy", quote: "Pitiful humans.", description: "A shape-shifting Homunculus." },
  "Greed": { name: "Greed", quote: "I want everything.", description: "A Homunculus with a thirst for power." },
  "Genos": { name: "Genos", quote: "I need more power.", description: "Saitama's cyborg disciple." },
  "Tatsumaki (Tornado of Terror)": { name: "Tatsumaki (Tornado of Terror)", quote: "Move it, you pest!", description: "A powerful psychic hero." },
  "Fubuki (Blizzard of Hell)": { name: "Fubuki (Blizzard of Hell)", quote: "I'll show you my strength.", description: "The leader of the Blizzard Group." },
  "Bang (Silver Fang)": { name: "Bang (Silver Fang)", quote: "Water Stream Rock Smashing Fist!", description: "A wise martial arts master." },
  "Speed-o'-Sound Sonic": { name: "Speed-o'-Sound Sonic", quote: "Saitama!", description: "A ninja who wants to defeat Saitama." },
  "King": { name: "King", quote: "I might look like the strongest man, but I'm actually just a gamer.", description: "Known as the strongest man on Earth, but essentially harmless." },
  "Kiyotaka Ayanokoji": { name: "Kiyotaka Ayanokoji", quote: "I have never thought of others as allies or friends. I only care about winning.", description: "A mysterious, highly intelligent student who tries to live a low-profile life." },
  "Suzune Horikita": { name: "Suzune Horikita", quote: "I don't need friends. I only need results.", description: "A cold, pragmatic, and highly intelligent student striving to reach Class A." },
  "Kei Karuizawa": { name: "Kei Karuizawa", quote: "I'll do whatever it takes to survive.", description: "A popular student with a traumatic past who relies on alliances for protection." },
  "Kikyou Kushida": { name: "Kikyou Kushida", quote: "I want to be loved by everyone.", description: "A student who hides a sinister, manipulative personality behind a cheerful facade." },
  "Kakeru Ryuuen": { name: "Kakeru Ryuuen", quote: "I like to crush those who think they're superior.", description: "An aggressive and manipulative class leader who uses underhanded tactics." },
  "Honami Ichinose": { name: "Honami Ichinose", quote: "I will protect my class no matter what.", description: "A kind, popular, and self-sacrificing class leader." },
  "Arisu Sakayanagi": { name: "Arisu Sakayanagi", quote: "I am the only one who can truly challenge you.", description: "A strategic genius who leads Class A with confidence." },
  "Yousuke Hirata": { name: "Yousuke Hirata", quote: "I will do anything to keep the class united.", description: "A selfless and responsible student dedicated to class harmony." },
  "Ken Sudo": { name: "Ken Sudo", quote: "I'll show them my strength on the court.", description: "A hot-headed, athletic student who is impulsive but passionate." },
  "Airi Sakura": { name: "Airi Sakura", quote: "I... I'm not good at interacting with others.", description: "A shy, introverted student with hidden artistic talents." },
  "Manabu Horikita": { name: "Manabu Horikita", quote: "You lack the resolve to change things.", description: "The strict and formidable Student Council President." },
  "Sae Chabashira": { name: "Sae Chabashira", quote: "Don't think I'll help you for free.", description: "A cunning teacher who pushes her students to grow through challenges." },
  "Miyabi Nagumo": { name: "Miyabi Nagumo", quote: "I will reshape the school in my own image.", description: "An ambitious and dominant Student Council President." },
  "Maya Sato": { name: "Maya Sato", quote: "Isn't it obvious?", description: "A girl who is outgoing and easily influenced." },
  "Kohei Katsuragi": { name: "Kohei Katsuragi", quote: "Stability is the most important thing.", description: "A cautious and pragmatic leader focused on steady progress." },
  "Hiyori Shiina": { name: "Hiyori Shiina", quote: "The library is a peaceful place.", description: "A bookworm who values intellect and tranquility." },
  "Takuya Yagami": { name: "Takuya Yagami", quote: "I will prove my superiority.", description: "A highly capable student hiding his true prowess." },
  "Ichika Amasawa": { name: "Ichika Amasawa", quote: "I'm just a curious observer.", description: "A playful yet manipulative student from the White Room." },
  "Denji": { name: "Denji", quote: "I want to have a normal life.", description: "A young man who merges with his dog demon." },
  "Makima": { name: "Makima", quote: "I have high expectations of you.", description: "A high-ranking public safety devil hunter." },
  "Power": { name: "Power", quote: "I'm the strongest devil!", description: "A blood fiend." },
  "Aki Hayakawa": { name: "Aki Hayakawa", quote: "I just want to kill the gun devil.", description: "A calm and serious public safety devil hunter." },
  "Pochita": { name: "Pochita", quote: "Woof!", description: "A small chainsaw devil." },
  "Himeno": { name: "Himeno", quote: "Aki, don't you die on me.", description: "A cigarette-loving devil hunter." },
  "Kobeni Higashiyama": { name: "Kobeni Higashiyama", quote: "I'm scared!", description: "A nervous but capable devil hunter." },
  "Kishibe": { name: "Kishibe", quote: "The craziest hunters are the ones who live the longest.", description: "A skilled and cynical devil hunter." },
  "Reze": { name: "Reze", quote: "Are you into explosions?", description: "A girl working as a soviet spy." },
  "Quanxi": { name: "Quanxi", quote: "I just want time for my girlfriends.", description: "The first devil hunter." },
  "Loid Forger (Twilight)": { name: "Loid Forger (Twilight)", quote: "For the sake of world peace, I must succeed.", description: "A top-tier master spy." },
  "Yor Forger (Thorn Princess)": { name: "Yor Forger (Thorn Princess)", quote: "I will kill for my family.", description: "An elite assassin working with a spy." },
  "Anya Forger": { name: "Anya Forger", quote: "Waku waku!", description: "A young telepath who loves peanuts." },
  "Bond Forger": { name: "Bond Forger", quote: "Borf!", description: "A psychic dog." },
  "Yuri Briar": { name: "Yuri Briar", quote: "I'll protect my sister!", description: "A dedicated secret police officer." },
  "Becky Blackbell": { name: "Becky Blackbell", quote: "Anya, let's go shopping!", description: "Anya's wealthy and sassy friend." },
  "Damian Desmond": { name: "Damian Desmond", quote: "Don't get cocky!", description: "The arrogant but sweet son of a target." },
  "Fiona Frost (Nightfall)": { name: "Fiona Frost (Nightfall)", quote: "I am the perfect partner for Twilight.", description: "Twilight's protege agent." },
  "Sylvia Sherwood": { name: "Sylvia Sherwood", quote: "Keep up the good work, Twilight.", description: "Loid's handler at WISE." },
  "Franky Franklin": { name: "Franky Franklin", quote: "I've got the intel you need.", description: "Loid's information broker." },
  "Takemichi Hanagaki": { name: "Takemichi Hanagaki", quote: "I'll never give up!", description: "A time-leaping delinquent." },
  "Manjiro Sano (Mikey)": { name: "Manjiro Sano (Mikey)", quote: "The Invincible Mikey.", description: "The leader of the Tokyo Manji Gang." },
  "Ken Ryuguji (Draken)": { name: "Ken Ryuguji (Draken)", quote: "Mikey, you're not alone.", description: "Mikey's reliable right-hand man." },
  "Keisuke Baji": { name: "Keisuke Baji", quote: "One for all, all for one.", description: "A loyal member of the Tokyo Manji Gang." },
  "Chifuyu Matsuno": { name: "Chifuyu Matsuno", quote: "Baji-san!", description: "Baji's loyal lieutenant." },
  "Takashi Mitsuya": { name: "Takashi Mitsuya", quote: "I have to be the pillar of my sisters.", description: "A kind and responsible delinquent." },
  "Kazutora Hanemiya": { name: "Kazutora Hanemiya", quote: "It's everyone's fault!", description: "A deeply troubled and unstable delinquent." },
  "Hinata Tachibana": { name: "Hinata Tachibana", quote: "I'll always be by your side.", description: "Takemichi's kind and courageous girlfriend." },
  "Tetta Kisaki": { name: "Tetta Kisaki", quote: "I will make them kneel before me.", description: "A ruthless and manipulative mastermind." },
  "Izana Kurokawa": { name: "Izana Kurokawa", quote: "I am the true king.", description: "The leader of Tenjiku." },
  "Asta": { name: "Asta", quote: "My magic is never giving up!", description: "A magic-less boy determined to be the Wizard King." },
  "Yuno Grinberryall": { name: "Yuno Grinberryall", quote: "I will be the Wizard King.", description: "Asta's rival and talented wind mage." },
  "Noelle Silva": { name: "Noelle Silva", quote: "I am royalty!", description: "A member of the Black Bulls with vast mana." },
  "Yami Sukehiro": { name: "Yami Sukehiro", quote: "Surpass your limits.", description: "The intimidating captain of the Black Bulls." },
  "Julius Novachrono": { name: "Julius Novachrono", quote: "I love magic!", description: "The current Wizard King." },
  "Magna Swing": { name: "Magna Swing", quote: "I'm the coolest mage around!", description: "A hot-headed fire mage and member of the Black Bulls." },
  "Luck Voltia": { name: "Luck Voltia", quote: "Let's have some fun!", description: "A battle-crazy lightning mage." },
  "Finral Roulacase": { name: "Finral Roulacase", quote: "I just want to be popular with the girls.", description: "A supportive spatial magic wizard." },
  "Vanessa Enoteca": { name: "Vanessa Enoteca", quote: "I love my booze!", description: "A thread magic user with a free-spirited nature." },
  "Mereoleona Vermillion": { name: "Mereoleona Vermillion", quote: "Training starts now!", description: "The immensely strong lioness of the Crimson Lion Kings." },
  "Licht": { name: "Licht", quote: "The elves deserve justice.", description: "The leader of the Eye of the Midnight Sun." },
  "Patolli": { name: "Patolli", quote: "I must fulfill my mission.", description: "A member of the elves who led the eye." },
  "Kirito (Kazuto Kirigaya)": { name: "Kirito (Kazuto Kirigaya)", quote: "I'll survive in this world.", description: "The Black Swordsman." },
  "Asuna Yuuki": { name: "Asuna Yuuki", quote: "I'll do my best to fight by your side.", description: "The Lightning Flash." },
  "Leafa (Suguha Kirigaya)": { name: "Leafa (Suguha Kirigaya)", quote: "I'll protect my brother.", description: "Kirito's cousin and a skilled fighter." },
  "Sinon (Shino Asada)": { name: "Sinon (Shino Asada)", quote: "I'll never miss a shot.", description: "A sharp-shooting sniper." },
  "Alice Zuberg": { name: "Alice Zuberg", quote: "I am an Integrity Knight.", description: "A chivalrous and powerful knight." },
  "Eugeo": { name: "Eugeo", quote: "Blue Rose Sword!", description: "Kirito's close friend and ally." },
  "Klein (Ryotaro Tsuboi)": { name: "Klein (Ryotaro Tsuboi)", quote: "I'm always here for you, Kirito!", description: "A loyal friend and swordsman." },
  "Agil (Andrew Gilbert Mills)": { name: "Agil (Andrew Gilbert Mills)", quote: "I'll provide the shop, you provide the skills.", description: "A helpful trader and ally." },
  "Silica (Keiko Ayano)": { name: "Silica (Keiko Ayano)", quote: "Pina, help me!", description: "A sweet girl who uses her familiar." },
  "Lisbeth (Rika Shinozaki)": { name: "Lisbeth (Rika Shinozaki)", quote: "I'll make you the best blade in the game.", description: "A talented blacksmith." },
  "Natsu Dragneel": { name: "Natsu Dragneel", quote: "I'm fired up now!", description: "The fire dragon slayer." },
  "Lucy Heartfilia": { name: "Lucy Heartfilia", quote: "Open, gate of the Celestial Spirit!", description: "A celestial spirit mage." },
  "Erza Scarlet": { name: "Erza Scarlet", quote: "I am the Titania!", description: "A fierce and powerful mage." },
  "Gray Fullbuster": { name: "Gray Fullbuster", quote: "Ice Make!", description: "An ice wizard with a wild streak." },
  "Happy": { name: "Happy", quote: "Aye!", description: "A flying blue cat." },
  "Wendy Marvell": { name: "Wendy Marvell", quote: "I'll heal you!", description: "A sky dragon slayer." },
  "Gajeel Redfox": { name: "Gajeel Redfox", quote: "I'm a man who lives by the iron!", description: "The iron dragon slayer." },
  "Juvia Lockser": { name: "Juvia Lockser", quote: "Gray-sama!", description: "The water mage of Fairy Tail." },
  "Mirajane Strauss": { name: "Mirajane Strauss", quote: "I'll show you my demon form.", description: "A kind waitress with a demonic power." },
  "Laxus Dreyar": { name: "Laxus Dreyar", quote: "I'm the strongest in the guild!", description: "The lightning dragon slayer." },
  "Zeref Dragneel": { name: "Zeref Dragneel", quote: "Death is the only escape.", description: "The dark wizard and immortal master." },
  "Mavis Vermillion": { name: "Mavis Vermillion", quote: "Fairy Heart is our pride.", description: "The founder of Fairy Tail." },
  "Natsuki Subaru": { name: "Natsuki Subaru", quote: "I'll die for the ones I love.", description: "A boy who can return after death." },
  "Emilia": { name: "Emilia", quote: "I'll be the ruler of this country.", description: "A kind half-elf candidate for the throne." },
  "Rem": { name: "Rem", quote: "I love you, Subaru-kun.", description: "A loyal maid who loves Subaru." },
  "Ram": { name: "Ram", quote: "Subaru, you are a fool.", description: "Rem's older sister." },
  "Puck": { name: "Puck", quote: "Sleep well, Lia.", description: "Emilia's spirit contractor." },
  "Beatrice": { name: "Beatrice", quote: "I suppose.", description: "The librarian of the Sanctuary and a spirit." },
  "Roswaal L. Mathers": { name: "Roswaal L. Mathers", quote: "Everything is according to plan.", description: "A powerful and eccentric mage." },
  "Echidna": { name: "Echidna", quote: "I am greedy for knowledge.", description: "The Witch of Greed." },
  "Garfiel Tinsel": { name: "Garfiel Tinsel", quote: "I'm the strongest!", description: "A warrior with immense loyalty." },
  "Otto Suwen": { name: "Otto Suwen", quote: "I'm just a merchant.", description: "Subaru's clever and reliable ally." },
  "Reinhard van Astrea": { name: "Reinhard van Astrea", quote: "I'm the Sword Saint.", description: "The strongest knight in the kingdom." },
  "Rintaro Okabe": { name: "Rintaro Okabe", quote: "El Psy Kongroo.", description: "A self-proclaimed mad scientist." },
  "Kurisu Makise": { name: "Kurisu Makise", quote: "I'm not a pervert!", description: "A brilliant neuroscientist." },
  "Mayuri Shiina": { name: "Mayuri Shiina", quote: "Tu-tu-ru!", description: "Okabe's kindest friend." },
  "Itaru Hashida (Daru)": { name: "Itaru Hashida (Daru)", quote: "I'm a super hacker.", description: "Okabe's super hacker friend." },
  "Suzuha Amane": { name: "Suzuha Amane", quote: "I'll change the future.", description: "A time traveler from the future." },
  "Ruka Urushibara": { name: "Ruka Urushibara", quote: "I hope I can stay as a girl.", description: "Okabe's kind friend." },
  "Faris NyanNyan": { name: "Faris NyanNyan", quote: "Nyaa!", description: "A maid who speaks in cat noises." },
  "Moeka Kiryu": { name: "Moeka Kiryu", quote: "Give me the IBN 5100.", description: "A mysterious message-obsessed girl." },
  "Shirou Emiya": { name: "Shirou Emiya", quote: "I will be a hero of justice.", description: "A mage who wants to protect others." },
  "Saber (Artoria Pendragon)": { name: "Saber (Artoria Pendragon)", quote: "I ask of you, are you my Master?", description: "The heroic spirit of King Arthur." },
  "Rin Tohsaka": { name: "Rin Tohsaka", quote: "I never regret my choices.", description: "A talented mage focused on excellence." },
  "Archer (EMIYA)": { name: "Archer (EMIYA)", quote: "My body is made of swords.", description: "A cynical heroic spirit." },
  "Gilgamesh": { name: "Gilgamesh", quote: "Faker!", description: "The king of heroes." },
  "Kiritsugu Emiya": { name: "Kiritsugu Emiya", quote: "A hero must sacrifice the few for the many.", description: "A cold-hearted magus killer." },
  "Kirei Kotomine": { name: "Kirei Kotomine", quote: "Rejoice, for your wish will finally come true.", description: "A priest with dark intentions." },
  "Illyasviel von Einzbern": { name: "Illyasviel von Einzbern", quote: "I'm the best maid ever!", description: "A powerful mage with a hidden edge." },
  "Rider (Medusa)": { name: "Rider (Medusa)", quote: "Trust in me, Master.", description: "A heroic spirit with a mystical gaze." },
  "Lancer (Cu Chulainn)": { name: "Lancer (Cu Chulainn)", quote: "My Lancer lance never misses.", description: "A ferocious heroic spirit." },
  "David Martinez": { name: "David Martinez", quote: "I'll be a legend.", description: "A kid with chrome who wants to reach Arasaka Tower." },
  "Lucy": { name: "Lucy", quote: "Let's go to the moon.", description: "A netrunner who wants freedom." },
  "Rebecca": { name: "Rebecca", quote: "This is for David!", description: "A trigger-happy mercenary." },
  "Maine": { name: "Maine", quote: "Be a leader.", description: "A powerful and respected edgerunner." },
  "Dorio": { name: "Dorio", quote: "I've got your back, Maine.", description: "A loyal partner to Maine." },
  "Kiwi": { name: "Kiwi", quote: "Every merc has a price.", description: "A cynical and skilled netrunner." },
  "Pilar": { name: "Pilar", quote: "You lookin' at me?", description: "A crazy choomba." },
  "Faraday": { name: "Faraday", quote: "Everything can be sold.", description: "A treacherous fixer." },
  "Adam Smasher": { name: "Adam Smasher", quote: "You look like a cut of f*ckable meat.", description: "The ultimate Arasaka enforcer." },
  "Shigeo Kageyama (Mob)": { name: "Shigeo Kageyama (Mob)", quote: "I don't need to use my power to be special.", description: "A psychic with immense but restrained power." },
  "Arataka Reigen": { name: "Arataka Reigen", quote: "Salt punch!", description: "Mob's master and mentor." },
  "Akashi Seijuro": { name: "Akashi Seijuro", quote: "I am absolute.", description: "The former captain of the Generation of Miracles." },
  "Kuroko Tetsuya": { name: "Kuroko Tetsuya", quote: "I am a shadow.", description: "The phantom sixth man of the Generation of Miracles." },
  "Midorima Shintaro": { name: "Midorima Shintaro", quote: "Man proposes, God disposes.", description: "A high-percentage three-point shooter." },
  "Hitsugaya Toshiro": { name: "Hitsugaya Toshiro", quote: "I will cut you down.", description: "Captain of the 10th Division." },
  "Shikamaru Nara": { name: "Shikamaru Nara", quote: "What a drag.", description: "A brilliant strategist." },
  "Osomatsu Matsuno": { name: "Osomatsu Matsuno", quote: "Let's be lazy!", description: "The eldest brother of the sextuplets." },
  "Ipin": { name: "Ipin", quote: "I am a killer!", description: "A young assassin acting as a child." },
  "Mami Tomoe": { name: "Mami Tomoe", quote: "You can't become a magical girl without making a wish.", description: "A veteran magical girl." },
  "Cure Mint": { name: "Cure Mint", quote: "The green earth is my witness!", description: "A protector of nature." },
  "Sailor Neptune": { name: "Sailor Neptune", quote: "Deep reflection!", description: "A guardian with the power of the sea." },
  "Michiru Kaiou": { name: "Michiru Kaiou", quote: "The sea is calling.", description: "A talented violinist and Sailor Guardian." },
  "Fushiguro Megumi": { name: "Fushiguro Megumi", quote: "With this treasure I summon, Eight-Handled Sword Divergent Sila Divine General Mahoraga!", description: "A calm, talented sorcerer who uses the Ten Shadows technique." },
  "Gintoki Sakata": { name: "Gintoki Sakata", quote: "Strawberry milk!", description: "The silver-haired samurai who runs the Yorozuya." },
  "Ash Ketchum": { name: "Ash Ketchum", quote: "I choose you!", description: "A young trainer aiming to be a Pokémon master." },
  "Iida Tenya": { name: "Iida Tenya", quote: "I am the class representative!", description: "A serious and highly motivated hero in training." },
  "Tsuyu Asui": { name: "Tsuyu Asui", quote: "Ribbit.", description: "A frog-like hero student." },
  "Kanna": { name: "Kanna", quote: "It's so fluffy!", description: "A small dragon girl dragon who is curious about the human world." },
  "Wei": { name: "Wei", quote: "...", description: "A stoic and powerful character." },
  "Rei Ayanami": { name: "Rei Ayanami", quote: "I am not a doll.", description: "The mysterious and quiet pilot of Unit-00." },
  "Hei": { name: "Hei", quote: "I don't look like I belong in this world, but I am.", description: "A powerful contractor known as the Black Reaper." },
  "Kallen Stadtfeld": { name: "Kallen Stadtfeld", quote: "I'll fight for those oppressed!", description: "A skilled pilot and member of the Black Knights." },
  "Mew Ichigo": { name: "Mew Ichigo", quote: "For the future of the earth!", description: "The feline hero who protects the world." },
  "Itoshi Rin": { name: "Itoshi Rin", quote: "Luck is for the weak.", description: "A talented and intense striker from Blue Lock." },
  "Hinata Hyuga": { name: "Hinata Hyuga", quote: "I'll always be behind you.", description: "A gentle ninja who loves Naruto." },
  "Claymore": { name: "Claymore", quote: "I fight to protect the weak.", description: "A warrior with immense strength." },
  "Sakura Haruno": { name: "Sakura Haruno", quote: "I've learned a lot from Tsunade-sama!", description: "A brilliant medical ninja." }
};

export const COLOUR_CHARACTER_MAP: Record<string, string> = {
  "crimson": "Akashi Seijuro",
  "cyan": "Kuroko Tetsuya",
  "emerald": "Midorima Shintaro",
  "navy": "Fushiguro Megumi",
  "cobalt": "Sasuke Uchiha",
  "tangerine": "Ichigo Kurosaki",
  "snow": "Hitsugaya Toshiro",
  "shadow": "Shikamaru Nara",
  "scarlet": "Kurapika",
  "electric blue": "Killua Zoldyck",
  "dark purple": "Leorio",
  "forest": "Gon Freecss",
  "ruby": "Osomatsu Matsuno",
  "sky": "Ipin",
  "lemon": "Mami Tomoe",
  "mint": "Cure Mint",
  "aquamarine": "Sailor Neptune",
  "teal": "Michiru Kaiou",
  "periwinkle": "Rem",
  "apricot": "Ram",
  "charcoal": "Guts",
  "ivory": "Griffith",
  "lavender": "Trunks",
  "magenta": "Nozomi Yumehara",
  "turquoise": "Bulma",
  "bronze": "Shiryu",
  "platinum": "Kaname Tosen",
  "obsidian": "Ulquiorra Cifer",
  "coral": "Nami",
  "denim": "Franky",
  "rose": "Mina Ashido",
  "wine": "Yor Forger",
  "indigo": "Itachi Uchiha",
  "olive": "Rock Lee",
  "mustard": "Might Guy",
  "ochre": "Pain",
  "sepia": "Jiraiya",
  "slate": "Kakashi Hatake",
  "vermilion": "Muzan Kibutsuji",
  "buff": "Inosuke Hashibira",
  "honey": "Honey Senpai",
  "midnight": "Dark Shadow",
  "rust": "Kenshin Himura",
  "amber": "Edward Elric",
  "steel": "Alphonse Elric",
  "smoke": "Smoker",
  "plum": "Revy",
  "lilac": "Shinobu Kocho",
  "wheat": "Vash the Stampede",
  "fuchsia": "Anko Mitarashi",
  "brass": "Jet Black",
  "topaz": "Kyo Sohma",
  "azure": "Lancer",
  "maroon": "Gaara",
  "sand": "Temari",
  "khaki": "Kankuro",
  "peach": "Akari",
  "burnt orange": "Bakugo Katsuki",
  "neon green": "Tatsumaki",
  "silver": "Gintoki Sakata",
  "gold": "Gilgamesh",
  "ash": "Ash Ketchum",
  "brick": "Iida Tenya",
  "moss": "Tsuyu Asui",
  "pearl": "Kanna",
  "onyx": "Wei",
  "ice blue": "Rei Ayanami",
  "pitch black": "Hei",
  "crimson moon": "Kallen Stadtfeld",
  "pale pink": "Mew Ichigo",
  "deep blue": "Itoshi Rin",
  "sunset": "Hinata Hyuga",
  "clay": "Claymore",
  "gunmetal": "Riza Hawkeye",
  "blossom": "Sakura Haruno"
  
};

export const FOOD_CHARACTER_MAP: Record<string, string> = {
  "ramen": "Naruto",
  "strawberry cake": "Erza Scarlet",
  "meat on the bone": "Luffy",
  "takoyaki": "Gun Park",
  "donut": "Ace",
  "coffee": "Kaneki",
  "sweets": "Gojo",
  "sukuna finger": "Yuji",
  "bread": "Sasha Braus",
  "milk": "Kageyama",
  "apple": "Ryuk",
  "omelet rice": "Sanji",
  "katsudon": "Yuri Katsuki",
  "chocolate bar": "Killua",
  "honey": "Honey Senpai",
  "potato chips": "Light Yagami",
  "onigiri": "Zoro",
  "mapo tofu": "Kotomine Kirei",
  "hamburger": "Bakugo",
  "curry": "Soma Yukihira",
  "sake": "Tsunade",
  "melon pan": "Shana",
  "miso soup": "Tanjiro",
  "taiyaki": "Gran Torino",
  "pudding": "Beerus",
  "creme brulee": "Ames",
  "anpan": "Anpanman",
  "shrimp tempura": "Inosuke",
  "banana": "Steins Gate",
  "pizza": "C.C.",
  "lemon": "Zenitsu",
  "hotdog": "Sonic",
  "cola": "Franky",
  "red bean bun": "Doraemon",
  "sushi": "Shizuma",
  "tofu": "Takumi Fujiwara",
  "bacon and eggs": "Howl",
  "strawberry milk": "Gintoki",
  "samosa": "Naruto",
  "butter chicken": "Gojo",
  "vindaloo": "Sukuna",
  "gulab jamun": "Tanjiro",
  "pani puri": "Luffy",
  "biryani": "Soma Yukihira",
  "masala dosa": "Sanji",
  "vada pav": "Gun Park",
  "dhokla": "Isagi Yoichi",
  "paneer tikka": "Bakugo",
  "chai": "Levi Ackerman",
  "lassi": "Kageyama",
  "rasgulla": "Rimuru Tempest",
  "jalebi": "Killua",
  "dal makhani": "Ichigo Kurosaki",
  "kulfi": "Shouto Todoroki",
  "naan": "Zoro",
  "pav bhaji": "Denji",
  "rajma chawal": "Eren Yeager",
  "shahi tukda": "Gilgamesh",
  "khichdi": "Shikamaru",
  "chole bhature": "Goku",
  "papadum": "Brook",
  "mango lassi": "Hinata Shoyo",
  "kaju katli": "Sesshomaru",
  "mishti doi": "Nezuko",
  "aloo paratha": "Might Guy",
  "bhajia": "Rock Lee",
  "tandoori chicken": "Endeavor",
  "malai kofta": "All Might",
  "saag paneer": "Gon Freecss",
  "fish curry": "Kisame",
  "kebab": "Zuku (Deku)",
  "momo": "Mina Ashido",
  "chicken 65": "Itachi Uchiha",
  "phirni": "Violet Evergarden",
  "shrikhand": "Erza Scarlet",
  "bhel puri": "Joseph Joestar",
  "idli": "Saitama",
  "litti chokha": "Goku",
  "misal pav": "Sukuna",
  "sarson ka saag": "Rock Lee",
  "makki di roti": "Might Guy",
  "koshimbir": "Yoichi Isagi",
  "shikanji": "Nagi Seishiro",
  "thandai": "Satoru Gojo",
  "baingan bharta": "Megumi Fushiguro",
  "daal baati churma": "Roronoa Zoro",
  "poha jalebi": "Tanjiro Kamado",
  "thepla": "Shikamaru Nara",
  "khandvi": "Bachira Meguru",
  "bhapa ilish": "Rin Itoshi",
  "chingri malai curry": "Sae Itoshi",
  "ghugni": "Yuji Itadori",
  "luchi alur dom": "Hinata Shoyo",
  "karela fry": "Levi Ackerman",
  "khakra": "Armin Arlert",
  "sabudana khichdi": "Kaneki Ken",
  "puran poli": "Ichigo Kurosaki",
  "katori chaat": "Nobara Kugisaki",
  "gajar ka halwa": "Todoroki Shoto",
  "rabri": "Zenitsu Agatsuma",
  "bedmi poori": "Inosuke Hashibira",
  "kadhi chawal": "Eren Yeager",
  "shahi paneer": "Gilgamesh",
  "golgappa": "Monkey D. Luffy",
  "mutton rogan josh": "Gun Park",
  "haleem": "Ervin Smith",
  "kheer": "Nezuko Kamado",
  "seviyan": "Kurapika",
  "murukku": "Barou Shoei",
  "bisibelebath": "Itoshi Rin",
  "medu vada": "Iida Tenya",
  "payasam": "Mitsuri Kanroji",
  "unniyappam": "Chopper",
  "kozhukkatta": "Doraemon",
  "sattu paratha": "Baki Hanma",
  "dhansak": "Sanji",
  "patra": "Kuroko Tetsuya"
};
